FROM golang:1.24.3-alpine AS build
WORKDIR /opt/app
COPY ./pkg ./pkg
COPY ./go.mod ./go.mod
COPY ./cmd/log_clear/main.go ./cmd/log_clear/main.go
RUN go build -o log_clear ./cmd/log_clear/main.go

FROM debian:bookworm
WORKDIR /opt/app
COPY --from=build /opt/app/log_clear ./log_clear
ENTRYPOINT [ "./log_clear" ]