FROM golang:1.24.3-alpine AS build
WORKDIR /opt/app
COPY ./pkg ./pkg
COPY ./go.mod ./go.mod
COPY ./cmd/hidden_file_and_dir/main.go ./cmd/hidden_file_and_dir/main.go
RUN go build -o hidden_file_and_dir ./cmd/hidden_file_and_dir/main.go

FROM debian:bookworm
WORKDIR /opt/app
COPY ./assets/myapp ./assets/myapp
COPY --from=build /opt/app/hidden_file_and_dir ./hidden_file_and_dir
ENTRYPOINT [ "./hidden_file_and_dir" ]