FROM golang:1.24.3-alpine AS build
WORKDIR /opt/app
COPY ./pkg ./pkg
COPY ./go.mod ./go.mod
COPY ./cmd/path_interception/main.go ./cmd/path_interception/main.go
RUN go build -o path_interception ./cmd/path_interception/main.go

FROM debian:bookworm
WORKDIR /opt/app
COPY ./assets/myapp ./assets/myapp
COPY --from=build /opt/app/path_interception ./path_interception
ENTRYPOINT [ "./path_interception" ]