FROM golang:1.24.3-alpine AS build
WORKDIR /opt/app
COPY ./pkg ./pkg
COPY ./go.mod ./go.mod
COPY ./main.go ./main.go
RUN go build -o clear_command_history ./main.go

FROM debian:bookworm
WORKDIR /opt/app
COPY ./assets/.bash_history ./assets/.bash_history
COPY --from=build /opt/app/clear_command_history ./clear_command_history
ENTRYPOINT [ "./clear_command_history" ]