FROM golang:1.24.3-alpine AS build
WORKDIR /opt/app
COPY ./pkg ./pkg
COPY ./go.mod ./go.mod
COPY ./cmd/http_get_request/main.go ./cmd/http_get_request/main.go
RUN go build -o http_get_request ./cmd/http_get_request/main.go

FROM debian:bookworm
WORKDIR /opt/app
RUN apt update && apt install -y curl
COPY ./assets/myapp ./assets/myapp
COPY --from=build /opt/app/http_get_request ./http_get_request
ENTRYPOINT [ "./http_get_request" ]