name: Доставка проекта на тестовый сервер

on:
  push:
    branches: [ main, develop ]
    
jobs:
  delivery:
    runs-on: [ self-hosted ]
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4

      - name: Копирование акутальной версии проекта в удобную директорию
        run: |
          rsync -a --delete ${{ github.workspace }} /home/user/