name: Доставка проекта на тестовый сервер

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: [ self-hosted, centos ]
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Копирование акутальной версии проекта в удобную директорию
        run: |
          rsync -a --delete ${{ github.workspace }} /home/user/

      - name: Сборка всего проекта
        run: |
          docker buildx bake
        working-directory: /home/user/abnormal-activity

  deploy:
    needs: build
    runs-on: [ centos ]
    steps:
      - name: Сборка и развертывание всех контейнеров
        run: |
          cd /home/user/abnormal-activity
          for service in $(docker compose config --services); do
            echo "Запускаю $service..."
            docker compose up "$service" --build
          done