name: Доставка проекта на тестовый сервер

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: [ centos ]
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4

      - name: Копирование акутальной версии проекта в удобную директорию
        run: |
          rsync -a --delete ${{ github.workspace }} /home/user/

      - name: Сборка всего проекта
        run: |
          docker buildx bake
        working-directory: /home/user/abnormal-activity

  deploy:
    needs: build
    runs-on: [ centos ]
    steps:
      - name: Сборка и развертывание всех контейнеров
        run: |
          for service in $(docker compose config --services); do
            echo "Запускаю $service..."
            docker compose up "$service" --build
          done
        working-directory: /home/user/abnormal-activity